### ISSUE TITLE
Astropy bug with numpy 1.24

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#105]
numpy 1.24 was released on December 18 and seems to have an incompatibility with astropy.  In brief, it's due to new `dtype` and `casting` args [allowed for some numpy functions](https://numpy.org/doc/stable/release/1.24.0-notes.html#casting-and-dtype-keyword-arguments-for-numpy-stack).  Specifically, [astropy's concatenate()](https://github.com/astropy/astropy/blob/87963074a50b14626fbd825536f384a6e96835af/astropy/units/quantity_helper/function_helpers.py#L380) doesn't have the new args [needed by numpy](https://github.com/numpy/numpy/blob/2f64274d360b25d509636897d5d39157080a42cc/numpy/core/shape_base.py#L471).

For now, I think we should change our build constraints everywhere to require `numpy<1.24`.

This causes an exception in UseCase_I, section 14, where we try to plot a circle, transformed to fk5, over an object in the image:
```
fig = plt.figure()

ax = fig.add_subplot(1, 1, 1, projection=WCS(sdss_rband_image[0].header))

interval = vis.PercentileInterval(99.9)
vmin,vmax = interval.get_limits(sdss_rband_image[0].data)
norm = vis.ImageNormalize(vmin=vmin, vmax=vmax, stretch=vis.LogStretch(1000))
ax.imshow(sdss_rband_image[0].data, cmap = 'gray_r', norm = norm, origin = 'lower')          
ax.scatter(ra, dec, transform=ax.get_transform('fk5'), s=500, edgecolor='red', facecolor='none')
```

**Comment by bsipocz** [comment]
This is a weird one but I'm not sure we could have done much about it in CI. We're testing dev astropy, released astropy with released numpy, but don't use dev numpy (as we don't really use that much numpy directly). I suppose we can add numpy dev testing, too, but it wouldn't help us much if upstream astropy is not paying attention to their numpy-dev and numpy release candidate testing.
