### ISSUE TITLE
Set up automated testing for notebooks

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#12]
Try to use Astropy's nbcollection package (see PR https://github.com/astropy/nbcollection/pull/12) to set up automated testing for the notebooks.  The tests probably should be run at least on PR creation/modification and merge.

**Comment by alex-treebeard** [comment]
hey there, I maintain a [pytest plugin](https://github.com/treebeardtech/nbmake) for this in case it helps, feedback very welcome.
