### ISSUE TITLE
MAINT: install astroquery using pip and the --pre option

### ISSUE THREAD

**Issue by stargaser** [NASA-NAVO/navo-workshop#122]
Based on the discussion in #118, our astroquery version is relatively old because we are installing from conda-forge. astroquery should always be installed with pip and using the --pre option. I don't know if this is possible in the environment.yml file, so maybe we should add the astroquery installation using pip as a separate step. Or if we moved away from conda...

**Comment by bsipocz** [comment]
see #121 for the fix
