### ISSUE TITLE
Exercise_I.ipynb - link to Ogle paper doesn't work

### ISSUE THREAD

**Issue by alaity47** [NASA-NAVO/navo-workshop#125]
In the rendered version of the notebook, the link seems fine (https://ui.adsabs.harvard.edu/abs/2016ApJ...817..109O/abstract)

But from the ipynb version, the link is as follows - clicking it from inside the notebook just redirects you to the front page of ADS:

https://ui.adsabs.harvard.edu//#abs/2016ApJ...817..109O/abstract

**Comment by bsipocz** [comment]
Interesting, I wonder where that extra hashmark is coming from
