### ISSUE TITLE
Make workshop presentable on NASA science platform

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#131]
Details TBD, but consider:

- authN
- environment setup (built ahead of time, automatic or user controlled?)

**Comment by stargaser** [comment]
After discussions including @trjaffe we decided not to try this on the Fornaxdev SMCE this time around. My [funding request](https://github.com/astropy/astropy-project/issues/367) to the Astropy Project to make a Jupyterhub for the Astropy workshop was approved. We could potentially use that setup as an alternative to mybinder.org for our workshop participants who need a backup solution.

**Comment by bsipocz** [comment]
I suppose we can close this for now and revisit next year? Reopen if disagree.
