### ISSUE TITLE
Directory from which to start Jupyterlab

### ISSUE THREAD

**Issue by stargaser** [NASA-NAVO/navo-workshop#156]
In [Step 7](https://github.com/NASA-NAVO/navo-workshop/blob/main/00_SETUP.md#7-starting-jupyterlab) of the setup instructions, we say to start Jupyterlab from the directory containing the notebooks. Now the notebooks are no longer in the top-level directory, but are split amongst `content/reference_notebooks` and `content/use_case_notebooks`. Should we instruct users to start Jupyterlab from the top-level and navigate down into `content/` and its subdirectories?

**Comment by tomdonaldson** [comment]
That's a good idea!
