### ISSUE TITLE
Re-write Catalog search Cheat Sheet to work for existing meta-data 

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#16]
... particularly the way searching for a TAP service doesn’t necessarily find you what you want.

**Comment by tomdonaldson** [comment]
May depend on how #17 is addressed.  If that is not addressed, we may need to work around the usability issues here.

**Comment by tomdonaldson** [comment]
This may now be a pyvo fix.  We can find things in the registry on the MAST registry UI, but not via a pyvo regsearch.  Working around this issue is messy:  somehow get them to find catalog TAP searches via first finding cone searches.

**Comment by theresadower** [comment]
There's a GitHub issue in pyvo for adding a flag for this behaviour. It stalled while we discussed the desirability of it given it also causes much duplicate info to be returned (one full result per aux or primary interface per each match). Can make a PR for it. https://github.com/astropy/pyvo/issues/238
