### ISSUE TITLE
Potentially assist IVOA Data Model WG with implementations utilizing Source model

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#20]
For a long time, the IVOA Data Model working group has tried to do both these things, which are theoretically mostly independent, but in practice closely related:

- Come up with a set of data models for representing sources (i.e., typical source catalog entries)
- Find an agreeable way to annotate VO Tables so that each row can represent one or more model instances with possible hierarchy (e.g., this Source with ID from column A, has this Coord from columns B, C, etc., as well as the LuminosityMeasurements from columns X, Y, and Z).

During the May 2021 interop, we hope to present some real-ish science cases that show:

- It's useful to know the model (maybe because if we have an instance of the model, we can do something useful in Astropy).
- It's possible to convey instances of interest via VOTable results from a catalog query.
- The same code can interpret results from at least 2 different catalogs (i.e., demonstrate interoperability).  
  - A possible example might be showing that we can automatically make color-color plots from HSC and PanSTARRS.
  - Another possible example could be plotting proper motions.

The implementations and input data are being collected in a separate repository.  See that for the many more details:  https://github.com/ivoa/dm-usecases

**Comment by stargaser** [comment]
Was this done for the May 2021 Interop? If not, should we remove the milestone?

**Comment by tomdonaldson** [comment]
Closing this as mostly out of data and unrelated to the workshop.
