### ISSUE TITLE
Work to clean up SDSS SIAP service a bit

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#38]
UseCase_I shows use of the SDSS SIAP service, but it has a couple quirks:

1. It requires `format=''` in the query.
2. When querying with a zero-radius position, we specify `intersect='covers'`.  Is that necessary?

**Comment by alaity47** [comment]
FYI as of last week I didn't seem to need the format='' anymore, so maybe the SDSS SIAP service has changed recently?  

(I actually came here to report that we should take out the blurb about that query needing that workaround)
