### ISSUE TITLE
Switch the repo CI to GitHub Actions?

### ISSUE THREAD

**Issue by stargaser** [NASA-NAVO/navo-workshop#50]
The workshop CI uses CircleCI and the setup is copied from what Adrian Price-Whelan set up for the [astropy-workshop](https://github.com/astropy/astropy-workshop) repo. Should we switch to GitHub Actions?

**Comment by tomdonaldson** [comment]
I deferred implementing something for #47 since switching CI schemes might change whether it's needed/desired.  If `download_file()` timeouts continue to be an issue in CI, then we can consider implementing #47 (or some other workaround).

**Comment by tomdonaldson** [comment]
The `pyvo` and `astropy` version updates were handled by #48.

**Comment by bsipocz** [comment]
Done in #62. Outstanding todo items to improve the overall CI experience is tracked in #63
