### ISSUE TITLE
Change name of default branch to `main`

### ISSUE THREAD

**Issue by stargaser** [NASA-NAVO/navo-workshop#51]
We should really follow what the Astropy Project has done and rename the `master` branch to `main`.

As I recall, Astropy has a guide but I can't find it. I found [this alternate recipe](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main).

**Comment by bsipocz** [comment]
I'm happy to get this done along with the CI sometime this week.

**Comment by bsipocz** [comment]
This has been done now, and PR #56 has the updates to the links.
