### ISSUE TITLE
list index out of range error in CS_Catalog_Queries.ipynb

### ISSUE THREAD

**Issue by ayyucedemirbas** [NASA-NAVO/navo-workshop#6]
Hello,

I am trying to run CS_Catalog_Queries.ipynb on Google colab. But I got an error message while running this cell:

> ##Use the one that's CFAZ. 
> ##Use list comprehension to check each service's short_name attribute and use the first.
> cfaz_cone_service = [s for s in services if 'CFAZ' in s.short_name][0] 
> 
> ##We are searching for sources within 10 arcminutes of M51. 
> results = cfaz_cone_service.search(pos=coord, radius=10*u.arcmin)
> results.to_table()

The error message is:

> IndexError                                Traceback (most recent call last)
> <ipython-input-7-9557074097dc> in <module>()
>       1 ## Use the one that's CFAZ.
>       2 ##  Use list comprehension to check each service's short_name attribute and use the first.
> ----> 3 cfaz_cone_service = [s for s in services if 'CFAZ' in s.short_name][0]
>       4 
>       5 ## We are searching for sources within 10 arcminutes of M51.
> 
> IndexError: list index out of range

Thank you so much!

**Comment by stargaser** [comment]
Thank you @ayyucedemirbas for opening this issue. I've tried these notebooks cells in a conda environment on my own machine, and also on Binder, and they are working.  I haven't tried these notebooks in Google Colab before. I tried this one and it fails at the "import pyvo" step. 

How are you installing dependencies for Google Colab? What is the output of `vo.__version__`?

You can view a rendered version of this notebook at https://nasa-navo.github.io/navo-workshop/CS_Catalog_Queries.html which shows what the table looks like in the preceding code cell.

**Comment by ayyucedemirbas** [comment]
Hello, you can install pyvo on colab with this command:

> !pip3 install pyvo

The version of pyvo is 1.1

**Comment by stargaser** [comment]
Thanks! I installed pyvo this way, into Google Colab, and the search for the 'CFAZ' service works for me. It all should work with pyvo 1.1 and the 4.0.1.post1 version of astropy that I see is already in Colab.

When astropy 4.1 is released, that version may break the notebooks, though we will try to be ready for it.

Would you please try the notebook again? With these archive searches, there is always a possibility that a service was down for a time.

**Comment by ayyucedemirbas** [comment]
It works now! Thank you so much!

**Comment by stargaser** [comment]
Great! Glad to hear it works now. I am closing the issue.
