### ISSUE TITLE
MAINT: consider switching to myst-nb format from ipynb

### ISSUE THREAD

**Issue by bsipocz** [NASA-NAVO/navo-workshop#69]
Having the notebooks as markdown in the repo could give a smoother repo experience, and it works rather nicely for notebooks that are stored empty with all their outputs to be generated on the fly. 

Some big projects are following this approach very successfully, e.g.:

https://github.com/numpy/numpy-tutorials#contributing

**Comment by tomdonaldson** [comment]
This is an interesting idea.  It might be fun and informative to look through an example or two while deciding.
