### ISSUE TITLE
Titles of blank exercises and worked out exercises in static rendering

### ISSUE THREAD

**Issue by j-sarmiento** [NASA-NAVO/navo-workshop#76]
A possible improvement for the static renderings of the notebooks would be to differentiate between the blank exercises and the worked out exercises.  The blank exercises and the corresponding worked out exercises have the same name so it can be confusing. Changing the titles to differentiate between the different workbooks would be helpful.

**Comment by bsipocz** [comment]
This is related to #66

**Comment by tomdonaldson** [comment]
Thank you for this suggestion.  We've added it to the broader issue #66.
