### ISSUE TITLE
Release pyvo with registry interface updates

### ISSUE THREAD

**Issue by tomdonaldson** [NASA-NAVO/navo-workshop#79]
The pyvo dev version has significant changes relative to the last release (v1.3), so a new new version should be released.  In addition to the usual mechanics of a release, we should:

- Evaluate the backward compatibility of #astropy/pyvo/pull/289 to see what versioning, deprecations, etc. may be needed.
- Look at the open PRs to see if there are easy reviews/merges that should be included.

**Comment by bsipocz** [comment]
v1.4 is out, so this can be closed.
