### ISSUE TITLE
Demonstrating adding markers to images

### ISSUE THREAD

**Issue by j-sarmiento** [NASA-NAVO/navo-workshop#81]
In UseCase_I, the chosen galaxy is indicated in some of the images by placing a marker (in this case a red ring) around it.  This is very useful, so I suggest that it is added to the Quick Reference guide or the CS files, as well as being made a part of Exercise_I.

**Comment by tomdonaldson** [comment]
Since the red ring is in the solution, and the overlay graphics are not core to what we're teaching, we've decided to close this.
