### ISSUE TITLE
BUG: cronjob is failing (but doesn't trigger notifications)

### ISSUE THREAD

**Issue by bsipocz** [NASA-NAVO/navo-workshop#86]
The cron job seems to be failing, and with the same error @trjaffe was running into when using the navo environment for another project. So I think this is very likely not an issue with the actual notebook content but some new version conflict of our dependencies (and the start of the failing CI jobs indeed highly correlate with the release of numpy 1.23).

Normally I get github notifications when cron jobs start to fail in my other projects, not sure why it's not the case for this repo, it maybe due to the fact that the devdeps workflow is allowed to fail and thus doesn't trigger notifications?

https://github.com/NASA-NAVO/navo-workshop/runs/7945316335?check_suite_focus=true

**Comment by pllim** [comment]
Yeah, I dunno where some of the cron job notifications go. I get them for astropy but somehow don't get for this other project I have admin access to. Maybe try to ask other co-admins and see if the notifications are in their spam folder or something.

**Comment by bsipocz** [comment]
I didn't get the cron, but finally I started getting the failing job notification, so maybe it was just a question of triggering the failure myself? I dunno either, and plan to keep this issue open at least until next week when the cron will run again.

**Comment by bsipocz** [comment]
> Maybe try to ask other co-admins and see if the notifications are in their spam folder or something.

I'm fairly certain that CI failures are not triggering notifications by default, and I remember that I had to opt in for them, and now getting astroquery and astroML, but that's just a small subset of repos where I'm both admin and am watching.

**Comment by bsipocz** [comment]
@pllim - the mystery is solved (thanks to the numpy folks for the pointer), it's only the last person touching the cron settings who gets the notification: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs
I'll ping you if/when we cook up a solution that addresses how to keep more people in the loop for those notification.

**Comment by pllim** [comment]
> the last person touching the cron settings

Hmm... I guess I can see why they do that but that is super confusing. Thanks for letting me know! 🙇‍♀️

**Comment by bsipocz** [comment]
well, I don't really see a good argument for it, those should go out to at least all the ones with write access who also watch the repo... Anyway, I'll look into a workaround as we'll need it here, as well as in many other repos.

**Comment by bsipocz** [comment]
I'm closing this here as it's a fully upstream issue, with the understanding that once we cook up a solution, I'll add it here, too.
